# Automatically generated by configure - do not modify
TARGET_I386=y
TARGET_NAME=i386
TARGET_BASE_ARCH=i386
TARGET_ABI_DIR=i386
CONFIG_USER_ONLY=y
CONFIG_QEMU_INTERP_PREFIX="/usr/gnemul/qemu-i386"
CONFIG_LINUX_USER=y
TARGET_XML_FILES= /home/happynote3966/SeQEMU_Second/SeQEMU/qemu/gdb-xml/i386-32bit.xml /home/happynote3966/SeQEMU_Second/SeQEMU/qemu/gdb-xml/i386-32bit-core.xml /home/happynote3966/SeQEMU_Second/SeQEMU/qemu/gdb-xml/i386-32bit-sse.xml
CONFIG_I386_DIS=y
CONFIG_I386_DIS=y
LDFLAGS+= 
QEMU_CFLAGS+=
