# Automatically generated by configure - do not modify
SRC_PATH=/home/happynote3966/SeQEMU_Second/SeQEMU/qemu/roms/vgabios
AS=as
CCAS=cc
CC=cc
BCC=bcc
CPP=cc -E
OBJCOPY=objcopy
IASL=iasl
LD=ld
RANLIB=ranlib
